baseurl = "https://goodwatch.org/"
title = "A Good Watch"
theme = "hugo_theme_robust"

#googleAnalytics = "UA-XXXXXXXX-XX" # Optional
#disqusShortname = "XYW"

[params]
  description = "A neighborly watch for radio engineers."
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  #googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  #fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  #logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/travis.png"
  name = "Travis Goodspeed KK4VCZ"
  description = "<p>Travis Goodspeed is a neighborly reverse engineer from Southern Appalachia.</p>"
  #facebook = "https://www.facebook.com/daisuke.tsuji.735"
  twitter = "https://twitter.com/travisgoodspeed"
  github = "https://github.com/travisgoodspeed"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.
